# Generated by Django 5.2.5 on 2025-08-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_colonel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='completed_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
