# Generated by Django 5.2.5 on 2025-08-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complete_colonel', '0002_mission_completed_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
